services:
  gateway:
    image: tinydex-gateway
    container_name: gateway
    env_file: .env
    ports:
      - 9300:9300

  host1:
    image: tinydex-host
    container_name: host1
    tmpfs: /tmp

  host2:
    image: tinydex-host
    container_name: host2
    tmpfs: /tmp

  host3:
    image: tinydex-host
    container_name: host3
    tmpfs: /tmp

  host4:
    image: tinydex-host
    container_name: host4
    tmpfs: /tmp

  host5:
    image: tinydex-host
    container_name: host5
    tmpfs: /tmp

  host6:
    image: tinydex-host
    container_name: host6
    tmpfs: /tmp

  node1:
    image: tinydex
    container_name: node1
    depends_on:
      - host1
    tmpfs: /tmp
    env_file: .env
    ports:
      - 9200:9101
    command: 0 host1 node1:9100

  node2:
    image: tinydex
    container_name: node2
    depends_on:
      - host2
    tmpfs: /tmp
    env_file: .env
    command: 0 host2 node2:9100

  node3:
    image: tinydex
    container_name: node3
    depends_on:
      - host3
    tmpfs: /tmp
    env_file: .env
    command: 0 host3 node3:9100

  node4:
    image: tinydex
    container_name: node4
    depends_on:
      - host4
    tmpfs: /tmp
    env_file: .env
    command: 1 host4 node4:9100

  node5:
    image: tinydex
    container_name: node5
    depends_on:
      - host5
    tmpfs: /tmp
    env_file: .env
    command: 1 host5 node5:9100

  node6:
    image: tinydex
    container_name: node6
    depends_on:
      - host6
    tmpfs: /tmp
    env_file: .env
    command: 1 host6 node6:9100
