services:
  gateway:
    image: nginx
    container_name: gateway
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2
      - node3

  node1:
    image: tinydex
    container_name: node1
    tmpfs: /tmp
    env_file: .env
    ports:
      - 9001:9000
      - 9101:9100
    command: node1

  node2:
    image: tinydex
    container_name: node2
    env_file: .env
    tmpfs: /tmp
    ports:
      - 9002:9000
      - 9102:9100
    command: node2

  node3:
    image: tinydex
    container_name: node3
    env_file: .env
    tmpfs: /tmp
    ports:
      - 9003:9000
      - 9103:9100
    command: node3
